### ISSUE TITLE
Exception not raised for files not in .txt format in indexer

### ISSUE THREAD

**Issue by AugustinJose1221** [PeARSearch/PeARS-orchard#21]

**Comment by minimalparts** [comment]
Thanks for the catch and the contribution to the PR. One thing, though: the fix with the 'accept' attribute controls what file types the user can pick from the file input dialog box. It does not prevent a user to force a wrong file into the input (e.g. by changing the file selection dropdown in the input dialog box). We should perhaps add extra validation checks on this.

One example: I can input a .txt in 'record pod from file' in the pod management tab (after messing with the file type in the input dialog box), and it will look as if the file were processed. 

Another example: if I input a .txt file in the wrong format in 'index from file' in the indexer tab, processing starts but hangs at 0%.

Anybody with some energy to fix this? :)

**Comment by nandajavarma** [comment]
I agree that rather than validating the file extension(which itself doesn't make much of a difference), it would be better if we add more validations. Currently we get a `list index out of range` when the format of the file is not the one recommended.
