### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by F3nd0** [PeARSearch/PeARS-orchard#5]
This repository appears to contain no licensing information. I believe that at least a file containing the licence (named “COPYING”, for example) and/or a notice in the README file (and ideally in every other file) should be added. For a more robust licence marking system, you might want to use something like [FSFE's REUSE practices](https://reuse.software/about/).

**Comment by minimalparts** [comment]
Thank you, you're completely right. We are still discussing but will sort this out asap.

**Comment by minimalparts** [comment]
Thanks again. We now have added a license file to the repo.
