### ISSUE TITLE
Small issues related to bootstrap update

### ISSUE THREAD

**Issue by minimalparts** [PeARSearch/PeARS-orchard#51]
Just a couple of things I have noticed.

1) The welcome message on first load is not centered on the page:
![image](https://user-images.githubusercontent.com/8198783/198217414-8a061ddc-1f26-4fa5-bb10-22b8f80bdca5.png)

2) There was a line to display personal notes in search results here: https://github.com/PeARSearch/PeARS-orchard/blob/e720fd5be8f02d626e919a72c79d9ba8e290202b/app/templates/search/results.html#L85
It seems to have gone in the new version.

**Comment by stultus** [comment]
So this should be fixed now :)
